### ISSUE TITLE
Timing the Stimulation Code

### ISSUE THREAD

**Issue by satabios** [multichannelsystems/McsUsbNet_Examples#4]
I'm trying to send continuous stimulations on MEA 2100. For which I was running a timer to detect the execution time for each time it traverses through the code as shown below:
`          

            watch.Start();
            cStgDevice.PrepareAndSendData(0, amplitude, duration, STG_DestinationEnumNet.channeldata_voltage);
            // connect all stimulation channels to the first trigger
            cStgDevice.SetupTrigger(0, new uint[] { 255 }, new uint[] { 255 }, new uint[] { 1 });

            // start the first trigger
            
            cStgDevice.SendStart(1);
            watch.Stop();`    

My input duration are in the order of milli-seconds, hence I have to provide such N trains for my signal. But to my surprise the stopwatch returned that it is taking ~(10-15)milli-seconds to complete one such stimulation cycle. If this is the case it defeats the purpose of the signal. Am I calculating the timing from the wrong points or if not how should I go about this?

**Comment by armwal** [comment]
Hi, stopping the stimulator, sending the data, then restarting it is not ideal if you want to switch between stimulation patterns within milliseconds, because as you've seen it takes a bit of time to prepare the stimulation pattern in the McsUsbNet.dll and send it to the stimulator due to e.g. delays in the USB transfer. If you have timing-critical stimulation, there are several options to deal with this (see chapter 6.2s and 6.3 in the McsUsbNet documentation):

- What kind of stimulation trains are you using? You can program quite complex patterns for the stimulator by using nested loops, so maybe it is an option for you to load one pattern on the stimulator that contains all trains. This would be the best option if you are simply repeating the same train with pauses in between, for example.
- You can also divide the memory of the stimulator into multiple segments, load a waveform pattern into each segment and then only switch between memory segments when you want to start the next train. Switching between segments happens within milliseconds
- You can assign different patterns to the available triggers (4, usually) and start them within microseconds
- You could use the "Streaming Mode" of the stimulator, not the "Download Mode". However, this is much more complex to program, so we usually recommend using the Download Mode of the stimulator.

Please have a look at the documentation for the McsUsbNet where you will also find snippets with example code.

**Comment by satabios** [comment]
@armwal  Definitely, I'll look into those sections of the documentation. I'm attaching a sample Temporal Raster [Plot ](https://indianinstituteofscience-my.sharepoint.com/:i:/g/personal/sathyaprakas_iisc_ac_in/EdTXbFmxf_FPv1bXvz0y2mQBlGnv5I80VLbuZ09_ueGopw?e=msQac7) for your reference, please do let me know your thoughts. Here the y-axis represents the electrodes and the x-axis defines the timeline. How should we approach this.

**Comment by armwal** [comment]
If I understand your picture correctly, you want to achieve (at least) 5 stimulation trains running at the same time that switch basically independently from each other between *on* and *off* without any breaks in between? Sorry, but I don't see a good way to realize this with the builtin stimulator of the MEA2100 and exact timing. 3 stimulation trains would be doable by assigning each one to a different `Stg`. More stimulation trains could be achieved by having 1 `Stg` continuously active (assuming all stimulation trains have the same stimulation amplitudes) and only changing the active electrodes with the `SetElectrodeEnable` call by setting all electrodes to 1 that need to be active and the others to 0. You would need to call `SetElectrodeEnable` at every time point when any of the stimulation trains change from *on* to *off*. But because executing the `SetElectrodeEnable` call and communicating with the stimulator via USB takes a variable amount of time, you won't have precise timing of the stimulation anymore.

As I said, based on your plot of the stimulation pattern I don't see a way to achieve exactly this pattern. I've asked the developer of the stimulator API for his thoughts, maybe he has some more ideas.

**Comment by satabios** [comment]
@armwal: Any leads from the API developer?

**Comment by JensMCS** [comment]
It is as Armwal said in his last post: You can only specify 3 different stimulation pattern, that can run at the same time. However its is possible to switch the used electrodes during the stimulation from one selected pattern of electrodes to the next one. This feature is called **list-mode**. 
For this there is the second argument `listmodeIndex` in the command `SetEelectrodeEnable` and `SetElectrodeDacMux`.
You need to define the sideband channel 1 as well and use bit 8 to indicate when the stimulation pattern should switch to the next electrode pattern. Listening to this bit of the sideband needs to be activated with the comand `SetListmodeTriggerSource`.
You need to define the range of different electrode pattern with the command `SetListmodeIndexRange`.
Finally the list-mode needs to be activated before you start the stimulation with `ListModeSendStart`.
For this kind of usage, it is recommended to run all three (or less) channels at the same time, because the electrode pattern change is **one** global change.
 
Segmented memory (which was mentioned in an earlier post) is not implemented for the MEA2100, but only on our standalone stimulators STG400x.

**Comment by satabios** [comment]
Can we replace the STG400x with a [Master-9](https://www.ampi.co.il/master-9) to send 3 or more different stimulation patterns? or can we introduce a [Di/o](https://www.multichannelsystems.com/products/dio) to bridge them like [this](https://indianinstituteofscience-my.sharepoint.com/:b:/g/personal/sathyaprakas_iisc_ac_in/EZLf168ya79FgNeryCdF4CgBKMlZJbA8b4bhO4Qb4wnt2g?e=d6daM7).

**Comment by armwal** [comment]
As far as I am aware there is no (easy) way to connect an external stimulator to the MEA2100 in a way that the stimulus will be applied via the MEA channels and the blanking circuit of the MEA2100 works properly. However, it could be possible to apply the stimulation patterns from the external stimulator via external electrodes/wires to the bath in the MEA or by soldering the connection to the stimulator to the contact pads on the MEA, but I don't know how feasible this is in practice. Our technical support should hopefully be able to help you with this, so please write an email to support@multichannelsystems.com to discuss this further.
